language: node_js
node_js:
  - "11.9.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn bump
