language: node_js
node_js:
  - "11.9.0"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn recommended-bump

before_deploy:
  - curl https://github.com/lindell/github-release-cli/releases/download/1.2.0/github-releaser-travis -L --output github-releaser && chmod +x github-releaser

deploy:
  provider: script
  script: ./github-releaser -draft -verbose
  skip_cleanup: true
  on:
    tags: true
